### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [OlesyaIv/jsonValidator#8]
Go ahead and implement the 2nd task.

**Comment by SemenMartynov** [comment]
Don't forget to update documentation for the gradle build.

**Comment by OlesyaIv** [comment]
Готово.

**Comment by SemenMartynov** [comment]
1. Follow git-flow! I don't see your commit in this thread!
2. Why do you add `chmod +x gradlew` to your documentation?
3. Can't run your project. Please, check everything before submitting.
```
BUILD SUCCESSFUL

Total time: 25.63 secs
Unable to find image 'task:latest' locally
docker: Error response from daemon: repository task not found: does not exist or no pull access.
See 'docker run --help'
```

**Comment by OlesyaIv** [comment]
Готово.

**Comment by SemenMartynov** [comment]
Checked
